import { Salon, Booking, Post, Comment, Transaction, Coupon, Payout, Dispute, Analytics, Review, TimeSlot } from '../types';

export const MOCK_SALONS: Salon[] = [
  {
    id: 's1',
    name: 'The Royal Barber',
    ownerName: 'Rajesh Kumar',
    phone: '+91 98765 43210',
    address: '12, MG Road, Connaught Place',
    city: 'New Delhi',
    pincode: '110001',
    category: 'Men',
    services: [
      { id: 'sv1', name: 'Haircut', price: 350, duration: 30, description: 'Classic precision haircut' },
      { id: 'sv2', name: 'Beard Trim', price: 200, duration: 20, description: 'Shape and trim beard' },
      { id: 'sv3', name: 'Hair Color', price: 800, duration: 60, description: 'Full hair coloring' },
      { id: 'sv4', name: 'Head Massage', price: 250, duration: 20, description: 'Relaxing head massage' },
      { id: 'sv5', name: 'Facial', price: 500, duration: 45, description: 'Deep cleansing facial' },
    ],
    staff: [
      { id: 'st1', name: 'Amit Sharma', role: 'Senior Barber' },
      { id: 'st2', name: 'Ravi Singh', role: 'Barber' },
      { id: 'st3', name: 'Suresh Patel', role: 'Stylist' },
    ],
    workingHours: [
      { day: 'Monday', isOpen: true, openTime: '09:00', closeTime: '20:00' },
      { day: 'Tuesday', isOpen: true, openTime: '09:00', closeTime: '20:00' },
      { day: 'Wednesday', isOpen: true, openTime: '09:00', closeTime: '20:00' },
      { day: 'Thursday', isOpen: true, openTime: '09:00', closeTime: '20:00' },
      { day: 'Friday', isOpen: true, openTime: '09:00', closeTime: '21:00' },
      { day: 'Saturday', isOpen: true, openTime: '08:00', closeTime: '21:00' },
      { day: 'Sunday', isOpen: false, openTime: '10:00', closeTime: '18:00' },
    ],
    photos: [
      'https://images.unsplash.com/photo-1585747860715-2ba37e788b70?w=800',
      'https://images.unsplash.com/photo-1503951914875-452162b0f3f1?w=800',
      'https://images.unsplash.com/photo-1621605815971-fbc98d665033?w=800',
    ],
    approvalStatus: 'Approved',
    rating: 4.8,
    reviewCount: 234,
    priceRange: '₹200 - ₹800',
    isOpen: true,
    distance: 1.2,
    description: 'Premium barbershop offering classic and modern cuts with expert barbers.',
    createdAt: '2024-01-15',
  },
  {
    id: 's2',
    name: 'Glamour Studio',
    ownerName: 'Priya Mehta',
    phone: '+91 87654 32109',
    address: '45, Linking Road, Bandra West',
    city: 'Mumbai',
    pincode: '400050',
    category: 'Women',
    services: [
      { id: 'sv6', name: 'Haircut & Styling', price: 600, duration: 60, description: 'Cut and style' },
      { id: 'sv7', name: 'Blowout', price: 400, duration: 45, description: 'Professional blowout' },
      { id: 'sv8', name: 'Hair Treatment', price: 1200, duration: 90, description: 'Deep conditioning' },
      { id: 'sv9', name: 'Manicure', price: 350, duration: 30, description: 'Classic manicure' },
      { id: 'sv10', name: 'Pedicure', price: 450, duration: 45, description: 'Relaxing pedicure' },
      { id: 'sv11', name: 'Facial', price: 800, duration: 60, description: 'Glow facial' },
    ],
    staff: [
      { id: 'st4', name: 'Neha Gupta', role: 'Senior Stylist' },
      { id: 'st5', name: 'Pooja Sharma', role: 'Nail Artist' },
      { id: 'st6', name: 'Kavita Rao', role: 'Skin Specialist' },
    ],
    workingHours: [
      { day: 'Monday', isOpen: true, openTime: '10:00', closeTime: '20:00' },
      { day: 'Tuesday', isOpen: true, openTime: '10:00', closeTime: '20:00' },
      { day: 'Wednesday', isOpen: false, openTime: '10:00', closeTime: '20:00' },
      { day: 'Thursday', isOpen: true, openTime: '10:00', closeTime: '20:00' },
      { day: 'Friday', isOpen: true, openTime: '10:00', closeTime: '21:00' },
      { day: 'Saturday', isOpen: true, openTime: '09:00', closeTime: '21:00' },
      { day: 'Sunday', isOpen: true, openTime: '10:00', closeTime: '18:00' },
    ],
    photos: [
      'https://images.unsplash.com/photo-1560066984-138dadb4c035?w=800',
      'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800',
      'https://images.unsplash.com/photo-1487412947147-5cebf100ffc2?w=800',
    ],
    approvalStatus: 'Approved',
    rating: 4.6,
    reviewCount: 189,
    priceRange: '₹350 - ₹1200',
    isOpen: true,
    distance: 2.5,
    description: 'Luxury beauty studio for women offering premium hair and skin treatments.',
    createdAt: '2024-02-10',
  },
  {
    id: 's3',
    name: 'Little Stars Salon',
    ownerName: 'Anita Verma',
    phone: '+91 76543 21098',
    address: '8, Koramangala 5th Block',
    city: 'Bangalore',
    pincode: '560095',
    category: 'Kids',
    services: [
      { id: 'sv12', name: 'Kids Haircut', price: 250, duration: 30, description: 'Fun kids haircut' },
      { id: 'sv13', name: 'Hair Wash & Style', price: 150, duration: 20, description: 'Gentle wash and style' },
      { id: 'sv14', name: 'Hair Color (Highlights)', price: 500, duration: 45, description: 'Fun highlights' },
    ],
    staff: [
      { id: 'st7', name: 'Sunita Devi', role: 'Kids Specialist' },
      { id: 'st8', name: 'Meena Kumari', role: 'Stylist' },
    ],
    workingHours: [
      { day: 'Monday', isOpen: true, openTime: '10:00', closeTime: '19:00' },
      { day: 'Tuesday', isOpen: true, openTime: '10:00', closeTime: '19:00' },
      { day: 'Wednesday', isOpen: true, openTime: '10:00', closeTime: '19:00' },
      { day: 'Thursday', isOpen: true, openTime: '10:00', closeTime: '19:00' },
      { day: 'Friday', isOpen: true, openTime: '10:00', closeTime: '19:00' },
      { day: 'Saturday', isOpen: true, openTime: '09:00', closeTime: '20:00' },
      { day: 'Sunday', isOpen: true, openTime: '10:00', closeTime: '17:00' },
    ],
    photos: [
      'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=800',
      'https://images.unsplash.com/photo-1519699047748-de8e457a634e?w=800',
    ],
    approvalStatus: 'Approved',
    rating: 4.9,
    reviewCount: 98,
    priceRange: '₹150 - ₹500',
    isOpen: true,
    distance: 0.8,
    description: 'Child-friendly salon with patient stylists and a fun environment for kids.',
    createdAt: '2024-03-05',
  },
  {
    id: 's4',
    name: 'Unisex Cuts & Style',
    ownerName: 'Vikram Nair',
    phone: '+91 65432 10987',
    address: '22, Anna Nagar East',
    city: 'Chennai',
    pincode: '600102',
    category: 'Unisex',
    services: [
      { id: 'sv15', name: 'Haircut', price: 300, duration: 30, description: 'Precision cut for all' },
      { id: 'sv16', name: 'Hair Color', price: 700, duration: 60, description: 'Full color treatment' },
      { id: 'sv17', name: 'Keratin Treatment', price: 2500, duration: 120, description: 'Smoothing treatment' },
      { id: 'sv18', name: 'Facial', price: 600, duration: 45, description: 'Rejuvenating facial' },
    ],
    staff: [
      { id: 'st9', name: 'Arjun Menon', role: 'Master Stylist' },
      { id: 'st10', name: 'Divya Krishnan', role: 'Color Specialist' },
    ],
    workingHours: [
      { day: 'Monday', isOpen: true, openTime: '09:00', closeTime: '21:00' },
      { day: 'Tuesday', isOpen: true, openTime: '09:00', closeTime: '21:00' },
      { day: 'Wednesday', isOpen: true, openTime: '09:00', closeTime: '21:00' },
      { day: 'Thursday', isOpen: true, openTime: '09:00', closeTime: '21:00' },
      { day: 'Friday', isOpen: true, openTime: '09:00', closeTime: '21:00' },
      { day: 'Saturday', isOpen: true, openTime: '08:00', closeTime: '22:00' },
      { day: 'Sunday', isOpen: true, openTime: '10:00', closeTime: '20:00' },
    ],
    photos: [
      'https://images.unsplash.com/photo-1562322140-8baeececf3df?w=800',
      'https://images.unsplash.com/photo-1605497788044-5a32c7078486?w=800',
    ],
    approvalStatus: 'Approved',
    rating: 4.5,
    reviewCount: 156,
    priceRange: '₹300 - ₹2500',
    isOpen: false,
    distance: 3.1,
    description: 'Modern unisex salon offering premium styling services for everyone.',
    createdAt: '2024-01-28',
  },
  {
    id: 's5',
    name: 'Scissors & Style',
    ownerName: 'Deepak Joshi',
    phone: '+91 54321 09876',
    address: '67, Sector 18, Noida',
    city: 'Noida',
    pincode: '201301',
    category: 'Men',
    services: [
      { id: 'sv19', name: 'Classic Haircut', price: 280, duration: 25, description: 'Traditional cut' },
      { id: 'sv20', name: 'Shave', price: 180, duration: 20, description: 'Hot towel shave' },
      { id: 'sv21', name: 'Hair Spa', price: 600, duration: 60, description: 'Nourishing hair spa' },
    ],
    staff: [
      { id: 'st11', name: 'Mohit Yadav', role: 'Barber' },
      { id: 'st12', name: 'Sanjay Tiwari', role: 'Senior Barber' },
    ],
    workingHours: [
      { day: 'Monday', isOpen: true, openTime: '08:00', closeTime: '20:00' },
      { day: 'Tuesday', isOpen: true, openTime: '08:00', closeTime: '20:00' },
      { day: 'Wednesday', isOpen: true, openTime: '08:00', closeTime: '20:00' },
      { day: 'Thursday', isOpen: true, openTime: '08:00', closeTime: '20:00' },
      { day: 'Friday', isOpen: true, openTime: '08:00', closeTime: '21:00' },
      { day: 'Saturday', isOpen: true, openTime: '07:00', closeTime: '21:00' },
      { day: 'Sunday', isOpen: false, openTime: '09:00', closeTime: '18:00' },
    ],
    photos: [
      'https://images.unsplash.com/photo-1599351431202-1e0f0137899a?w=800',
      'https://images.unsplash.com/photo-1493256338651-d82f7acb2b38?w=800',
    ],
    approvalStatus: 'Approved',
    rating: 4.3,
    reviewCount: 87,
    priceRange: '₹180 - ₹600',
    isOpen: true,
    distance: 4.2,
    description: 'Affordable and quality barbershop with experienced barbers.',
    createdAt: '2024-04-12',
  },
  {
    id: 's6',
    name: 'Beauty Bliss Parlour',
    ownerName: 'Sunita Agarwal',
    phone: '+91 43210 98765',
    address: '33, Hazratganj',
    city: 'Lucknow',
    pincode: '226001',
    category: 'Women',
    services: [
      { id: 'sv22', name: 'Bridal Makeup', price: 5000, duration: 180, description: 'Complete bridal look' },
      { id: 'sv23', name: 'Waxing (Full Body)', price: 800, duration: 60, description: 'Full body waxing' },
      { id: 'sv24', name: 'Threading', price: 80, duration: 15, description: 'Eyebrow threading' },
      { id: 'sv25', name: 'Haircut', price: 400, duration: 45, description: 'Precision cut' },
    ],
    staff: [
      { id: 'st13', name: 'Rekha Mishra', role: 'Makeup Artist' },
      { id: 'st14', name: 'Geeta Pandey', role: 'Beautician' },
    ],
    workingHours: [
      { day: 'Monday', isOpen: true, openTime: '09:00', closeTime: '19:00' },
      { day: 'Tuesday', isOpen: true, openTime: '09:00', closeTime: '19:00' },
      { day: 'Wednesday', isOpen: true, openTime: '09:00', closeTime: '19:00' },
      { day: 'Thursday', isOpen: true, openTime: '09:00', closeTime: '19:00' },
      { day: 'Friday', isOpen: true, openTime: '09:00', closeTime: '20:00' },
      { day: 'Saturday', isOpen: true, openTime: '08:00', closeTime: '20:00' },
      { day: 'Sunday', isOpen: true, openTime: '10:00', closeTime: '17:00' },
    ],
    photos: [
      'https://images.unsplash.com/photo-1470259078422-826894b933aa?w=800',
      'https://images.unsplash.com/photo-1516975080664-ed2fc6a32937?w=800',
    ],
    approvalStatus: 'Approved',
    rating: 4.7,
    reviewCount: 312,
    priceRange: '₹80 - ₹5000',
    isOpen: true,
    distance: 1.8,
    description: 'Full-service beauty parlour specializing in bridal and special occasion looks.',
    createdAt: '2023-12-20',
  },
];

export const MOCK_PENDING_SALONS: Salon[] = [
  {
    id: 'ps1',
    name: 'New Wave Cuts',
    ownerName: 'Rahul Sharma',
    phone: '+91 99887 76655',
    address: '15, Sector 22, Gurgaon',
    city: 'Gurgaon',
    pincode: '122001',
    category: 'Men',
    services: [
      { id: 'psv1', name: 'Haircut', price: 300, duration: 30, description: 'Modern cuts' },
    ],
    staff: [],
    workingHours: [],
    photos: ['https://images.unsplash.com/photo-1503951914875-452162b0f3f1?w=800'],
    approvalStatus: 'Pending',
    rating: 0,
    reviewCount: 0,
    priceRange: '₹300',
    isOpen: false,
    createdAt: '2025-02-20',
  },
];

export const MOCK_BOOKINGS: Booking[] = [
  {
    id: 'b1',
    customerId: 'u1',
    customerName: 'Demo User',
    salonId: 's1',
    salonName: 'The Royal Barber',
    services: [{ id: 'sv1', name: 'Haircut', price: 350, duration: 30 }],
    staffId: 'st1',
    staffName: 'Amit Sharma',
    date: '2025-02-28',
    timeSlot: '10:00 AM',
    status: 'Accepted',
    paymentStatus: 'Paid',
    totalAmount: 350,
    createdAt: '2025-02-25',
  },
  {
    id: 'b2',
    customerId: 'u1',
    customerName: 'Demo User',
    salonId: 's2',
    salonName: 'Glamour Studio',
    services: [
      { id: 'sv6', name: 'Haircut & Styling', price: 600, duration: 60 },
      { id: 'sv9', name: 'Manicure', price: 350, duration: 30 },
    ],
    date: '2025-02-15',
    timeSlot: '02:00 PM',
    status: 'Completed',
    paymentStatus: 'Paid',
    totalAmount: 950,
    createdAt: '2025-02-12',
  },
  {
    id: 'b3',
    customerId: 'u1',
    customerName: 'Demo User',
    salonId: 's3',
    salonName: 'Little Stars Salon',
    services: [{ id: 'sv12', name: 'Kids Haircut', price: 250, duration: 30 }],
    date: '2025-01-20',
    timeSlot: '11:00 AM',
    status: 'Cancelled',
    paymentStatus: 'Refunded',
    totalAmount: 250,
    createdAt: '2025-01-18',
  },
  {
    id: 'b4',
    customerId: 'u1',
    customerName: 'Demo User',
    salonId: 's4',
    salonName: 'Unisex Cuts & Style',
    services: [{ id: 'sv17', name: 'Keratin Treatment', price: 2500, duration: 120 }],
    date: '2025-03-05',
    timeSlot: '03:00 PM',
    status: 'Pending',
    paymentStatus: 'Paid',
    totalAmount: 2500,
    createdAt: '2025-02-26',
  },
];

export const MOCK_REVIEWS: Review[] = [
  {
    id: 'r1',
    salonId: 's1',
    customerId: 'u1',
    customerName: 'Arjun Kapoor',
    rating: 5,
    text: 'Excellent service! Amit gave me the best haircut I\'ve had in years. Very professional and clean environment.',
    createdAt: '2025-02-20',
  },
  {
    id: 'r2',
    salonId: 's1',
    customerId: 'u2',
    customerName: 'Rohit Verma',
    rating: 4,
    text: 'Good experience overall. The beard trim was perfect. Slightly long wait time but worth it.',
    createdAt: '2025-02-15',
  },
  {
    id: 'r3',
    salonId: 's1',
    customerId: 'u3',
    customerName: 'Siddharth Malhotra',
    rating: 5,
    text: 'Best barber shop in Delhi! Always consistent quality. Highly recommend.',
    createdAt: '2025-02-10',
  },
];

export const MOCK_POSTS: Post[] = [
  {
    id: 'p1',
    authorId: 's1',
    authorName: 'The Royal Barber',
    authorPhoto: 'https://images.unsplash.com/photo-1585747860715-2ba37e788b70?w=100',
    authorType: 'owner',
    salonId: 's1',
    imageUrl: 'https://images.unsplash.com/photo-1503951914875-452162b0f3f1?w=600',
    caption: 'Fresh cuts for the weekend! Book your slot now 💈',
    hashtags: ['#haircut', '#barber', '#freshcut', '#delhi'],
    likeCount: 142,
    commentCount: 18,
    isLiked: false,
    createdAt: '2025-02-25',
  },
  {
    id: 'p2',
    authorId: 's2',
    authorName: 'Glamour Studio',
    authorPhoto: 'https://images.unsplash.com/photo-1560066984-138dadb4c035?w=100',
    authorType: 'owner',
    salonId: 's2',
    imageUrl: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=600',
    caption: 'Transform your look with our premium hair treatments ✨',
    hashtags: ['#hairtreatment', '#glamour', '#beauty', '#mumbai'],
    likeCount: 289,
    commentCount: 34,
    isLiked: true,
    createdAt: '2025-02-24',
  },
  {
    id: 'p3',
    authorId: 'u1',
    authorName: 'Priya Sharma',
    authorType: 'customer',
    imageUrl: 'https://images.unsplash.com/photo-1487412947147-5cebf100ffc2?w=600',
    caption: 'Loving my new look from Glamour Studio! 😍',
    hashtags: ['#newlook', '#hairgoals', '#salon'],
    likeCount: 67,
    commentCount: 8,
    isLiked: false,
    createdAt: '2025-02-23',
  },
  {
    id: 'p4',
    authorId: 's3',
    authorName: 'Little Stars Salon',
    authorPhoto: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=100',
    authorType: 'owner',
    salonId: 's3',
    imageUrl: 'https://images.unsplash.com/photo-1519699047748-de8e457a634e?w=600',
    caption: 'Making every kid feel like a star! 🌟 Special weekend offers available.',
    hashtags: ['#kidssalon', '#kidshaircut', '#bangalore'],
    likeCount: 198,
    commentCount: 22,
    isLiked: false,
    createdAt: '2025-02-22',
  },
];

export const MOCK_COMMENTS: Comment[] = [
  {
    id: 'c1',
    postId: 'p1',
    authorId: 'u1',
    authorName: 'Rahul Gupta',
    text: 'Amazing work! Will definitely book this weekend.',
    createdAt: '2025-02-25',
  },
  {
    id: 'c2',
    postId: 'p1',
    authorId: 'u2',
    authorName: 'Amit Singh',
    text: 'Best barber in town! 💯',
    createdAt: '2025-02-25',
  },
];

export const MOCK_TRANSACTIONS: Transaction[] = [
  {
    id: 't1',
    type: 'debit',
    description: 'Booking at The Royal Barber',
    amount: 350,
    date: '2025-02-25',
    bookingId: 'b1',
  },
  {
    id: 't2',
    type: 'credit',
    description: 'Referral reward - Friend joined',
    amount: 100,
    date: '2025-02-20',
  },
  {
    id: 't3',
    type: 'debit',
    description: 'Booking at Glamour Studio',
    amount: 950,
    date: '2025-02-15',
    bookingId: 'b2',
  },
  {
    id: 't4',
    type: 'credit',
    description: 'Refund - Cancelled booking',
    amount: 250,
    date: '2025-01-21',
    bookingId: 'b3',
  },
  {
    id: 't5',
    type: 'credit',
    description: 'Cashback reward',
    amount: 50,
    date: '2025-01-15',
  },
];

export const MOCK_COUPONS: Coupon[] = [
  {
    id: 'cp1',
    code: 'FIRST50',
    discountType: 'percent',
    discountValue: 50,
    minCartValue: 300,
    expiryDate: '2025-03-31',
    usageLimit: 1,
    usedCount: 0,
    isActive: true,
  },
  {
    id: 'cp2',
    code: 'SAVE100',
    discountType: 'flat',
    discountValue: 100,
    minCartValue: 500,
    expiryDate: '2025-04-30',
    usageLimit: 100,
    usedCount: 45,
    isActive: true,
  },
  {
    id: 'cp3',
    code: 'WOMEN20',
    discountType: 'percent',
    discountValue: 20,
    minCartValue: 400,
    expiryDate: '2025-03-15',
    usageLimit: 200,
    usedCount: 89,
    category: 'Women',
    isActive: true,
  },
];

export const MOCK_PAYOUTS: Payout[] = [
  {
    id: 'py1',
    salonId: 's1',
    salonName: 'The Royal Barber',
    amount: 12500,
    period: 'Feb 17-23, 2025',
    status: 'Pending',
    createdAt: '2025-02-23',
  },
  {
    id: 'py2',
    salonId: 's2',
    salonName: 'Glamour Studio',
    amount: 28900,
    period: 'Feb 17-23, 2025',
    status: 'Pending',
    createdAt: '2025-02-23',
  },
  {
    id: 'py3',
    salonId: 's3',
    salonName: 'Little Stars Salon',
    amount: 8400,
    period: 'Feb 10-16, 2025',
    status: 'Processed',
    createdAt: '2025-02-16',
  },
];

export const MOCK_DISPUTES: Dispute[] = [
  {
    id: 'd1',
    bookingId: 'b2',
    customerName: 'Priya Sharma',
    salonName: 'Glamour Studio',
    reason: 'Service quality was not as described. Requested refund.',
    amount: 950,
    status: 'Open',
    createdAt: '2025-02-16',
  },
];

export const MOCK_ANALYTICS: Analytics = {
  totalBookings: 1247,
  gmv: 892500,
  platformRevenue: 89250,
  cancellationRate: 8.5,
  topSalons: [
    { name: 'Beauty Bliss Parlour', bookings: 312 },
    { name: 'The Royal Barber', bookings: 234 },
    { name: 'Glamour Studio', bookings: 189 },
    { name: 'Unisex Cuts & Style', bookings: 156 },
    { name: 'Little Stars Salon', bookings: 98 },
  ],
  bookingsByDay: [
    { day: 'Mon', count: 145 },
    { day: 'Tue', count: 132 },
    { day: 'Wed', count: 118 },
    { day: 'Thu', count: 156 },
    { day: 'Fri', count: 198 },
    { day: 'Sat', count: 267 },
    { day: 'Sun', count: 231 },
  ],
  revenueByMonth: [
    { month: 'Sep', revenue: 62000 },
    { month: 'Oct', revenue: 71000 },
    { month: 'Nov', revenue: 68000 },
    { month: 'Dec', revenue: 89000 },
    { month: 'Jan', revenue: 95000 },
    { month: 'Feb', revenue: 89250 },
  ],
};

export function generateTimeSlots(date: string): TimeSlot[] {
  const slots: TimeSlot[] = [];
  const times = [
    '09:00 AM', '09:30 AM', '10:00 AM', '10:30 AM', '11:00 AM', '11:30 AM',
    '12:00 PM', '12:30 PM', '01:00 PM', '01:30 PM', '02:00 PM', '02:30 PM',
    '03:00 PM', '03:30 PM', '04:00 PM', '04:30 PM', '05:00 PM', '05:30 PM',
    '06:00 PM', '06:30 PM', '07:00 PM',
  ];
  const unavailableIndices = [2, 5, 8, 11, 14];
  times.forEach((time, idx) => {
    slots.push({
      id: `slot-${idx}`,
      time,
      isAvailable: !unavailableIndices.includes(idx),
    });
  });
  return slots;
}
