import React, {
  createContext,
  useContext,
  useState,
  useEffect,
  type ReactNode,
} from "react";

type Language = "en" | "hi";

interface AppContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<string, Record<Language, string>> = {
  // Navigation
  "nav.home": { en: "Home", hi: "होम" },
  "nav.browse": { en: "Browse", hi: "खोजें" },
  "nav.bookings": { en: "Bookings", hi: "बुकिंग" },
  "nav.wallet": { en: "Wallet", hi: "वॉलेट" },
  "nav.profile": { en: "Profile", hi: "प्रोफाइल" },
  "nav.feed": { en: "Feed", hi: "फीड" },
  "nav.blog": { en: "Blog", hi: "ब्लॉग" },
  "nav.faq": { en: "FAQ", hi: "सहायता" },
  "nav.contact": { en: "Contact", hi: "संपर्क" },
  "nav.dashboard": { en: "Dashboard", hi: "डैशबोर्ड" },
  "nav.admin": { en: "Admin", hi: "एडमिन" },
  "nav.login": { en: "Login", hi: "लॉगिन" },
  "nav.logout": { en: "Logout", hi: "लॉगआउट" },

  // Common
  "common.loading": { en: "Loading...", hi: "लोड हो रहा है..." },
  "common.error": { en: "Something went wrong", hi: "कुछ गलत हुआ" },
  "common.save": { en: "Save", hi: "सहेजें" },
  "common.cancel": { en: "Cancel", hi: "रद्द करें" },
  "common.submit": { en: "Submit", hi: "जमा करें" },
  "common.edit": { en: "Edit", hi: "संपादित करें" },
  "common.delete": { en: "Delete", hi: "हटाएं" },
  "common.confirm": { en: "Confirm", hi: "पुष्टि करें" },
  "common.back": { en: "Back", hi: "वापस" },
  "common.next": { en: "Next", hi: "अगला" },
  "common.search": { en: "Search", hi: "खोजें" },
  "common.filter": { en: "Filter", hi: "फ़िल्टर" },
  "common.all": { en: "All", hi: "सभी" },
  "common.view": { en: "View", hi: "देखें" },
  "common.close": { en: "Close", hi: "बंद करें" },
  "common.yes": { en: "Yes", hi: "हाँ" },
  "common.no": { en: "No", hi: "नहीं" },
  "common.or": { en: "or", hi: "या" },
  "common.and": { en: "and", hi: "और" },
  "common.from": { en: "From", hi: "से" },
  "common.to": { en: "To", hi: "तक" },
  "common.date": { en: "Date", hi: "तारीख" },
  "common.time": { en: "Time", hi: "समय" },
  "common.status": { en: "Status", hi: "स्थिति" },
  "common.amount": { en: "Amount", hi: "राशि" },
  "common.name": { en: "Name", hi: "नाम" },
  "common.email": { en: "Email", hi: "ईमेल" },
  "common.phone": { en: "Phone", hi: "फोन" },
  "common.address": { en: "Address", hi: "पता" },
  "common.city": { en: "City", hi: "शहर" },
  "common.rating": { en: "Rating", hi: "रेटिंग" },
  "common.reviews": { en: "Reviews", hi: "समीक्षाएं" },
  "common.services": { en: "Services", hi: "सेवाएं" },
  "common.price": { en: "Price", hi: "मूल्य" },
  "common.duration": { en: "Duration", hi: "अवधि" },
  "common.category": { en: "Category", hi: "श्रेणी" },
  "common.description": { en: "Description", hi: "विवरण" },
  "common.image": { en: "Image", hi: "छवि" },
  "common.upload": { en: "Upload", hi: "अपलोड करें" },
  "common.noData": { en: "No data found", hi: "कोई डेटा नहीं मिला" },
  "common.tryAgain": { en: "Try Again", hi: "पुनः प्रयास करें" },
  "common.bookNow": { en: "Book Now", hi: "अभी बुक करें" },
  "common.viewAll": { en: "View All", hi: "सभी देखें" },
  "common.readMore": { en: "Read More", hi: "और पढ़ें" },
  "common.language": { en: "Language", hi: "भाषा" },
  "common.english": { en: "English", hi: "अंग्रेजी" },
  "common.hindi": { en: "Hindi", hi: "हिंदी" },
  "common.minutes": { en: "min", hi: "मिनट" },
  "common.perService": { en: "per service", hi: "प्रति सेवा" },
  "common.open": { en: "Open", hi: "खुला" },
  "common.closed": { en: "Closed", hi: "बंद" },
  "common.verified": { en: "Verified", hi: "सत्यापित" },
  "common.pending": { en: "Pending", hi: "लंबित" },
  "common.approved": { en: "Approved", hi: "स्वीकृत" },
  "common.rejected": { en: "Rejected", hi: "अस्वीकृत" },
  "common.active": { en: "Active", hi: "सक्रिय" },
  "common.inactive": { en: "Inactive", hi: "निष्क्रिय" },
  "common.completed": { en: "Completed", hi: "पूर्ण" },
  "common.cancelled": { en: "Cancelled", hi: "रद्द" },
  "common.accepted": { en: "Accepted", hi: "स्वीकृत" },
  "common.declined": { en: "Declined", hi: "अस्वीकृत" },
  "common.processing": { en: "Processing", hi: "प्रक्रिया में" },
  "common.paid": { en: "Paid", hi: "भुगतान किया" },
  "common.unpaid": { en: "Unpaid", hi: "अभुगतान" },
  "common.refunded": { en: "Refunded", hi: "वापस किया" },
  "common.total": { en: "Total", hi: "कुल" },
  "common.subtotal": { en: "Subtotal", hi: "उप-कुल" },
  "common.discount": { en: "Discount", hi: "छूट" },
  "common.tax": { en: "Tax", hi: "कर" },
  "common.commission": { en: "Commission", hi: "कमीशन" },
  "common.balance": { en: "Balance", hi: "शेष राशि" },
  "common.earnings": { en: "Earnings", hi: "कमाई" },
  "common.payout": { en: "Payout", hi: "भुगतान" },
  "common.transaction": { en: "Transaction", hi: "लेनदेन" },
  "common.history": { en: "History", hi: "इतिहास" },
  "common.today": { en: "Today", hi: "आज" },
  "common.week": { en: "Week", hi: "सप्ताह" },
  "common.month": { en: "Month", hi: "महीना" },
  "common.year": { en: "Year", hi: "वर्ष" },
  "common.staff": { en: "Staff", hi: "स्टाफ" },
  "common.slot": { en: "Slot", hi: "स्लॉट" },
  "common.slots": { en: "Slots", hi: "स्लॉट्स" },
  "common.available": { en: "Available", hi: "उपलब्ध" },
  "common.booked": { en: "Booked", hi: "बुक किया" },
  "common.holiday": { en: "Holiday", hi: "छुट्टी" },
  "common.coupon": { en: "Coupon", hi: "कूपन" },
  "common.apply": { en: "Apply", hi: "लागू करें" },
  "common.remove": { en: "Remove", hi: "हटाएं" },
  "common.copy": { en: "Copy", hi: "कॉपी करें" },
  "common.share": { en: "Share", hi: "शेयर करें" },
  "common.report": { en: "Report", hi: "रिपोर्ट करें" },
  "common.like": { en: "Like", hi: "पसंद" },
  "common.comment": { en: "Comment", hi: "टिप्पणी" },
  "common.follow": { en: "Follow", hi: "फॉलो करें" },
  "common.unfollow": { en: "Unfollow", hi: "अनफॉलो करें" },
  "common.post": { en: "Post", hi: "पोस्ट" },
  "common.message": { en: "Message", hi: "संदेश" },
  "common.send": { en: "Send", hi: "भेजें" },
  "common.male": { en: "Male", hi: "पुरुष" },
  "common.female": { en: "Female", hi: "महिला" },
  "common.kids": { en: "Kids", hi: "बच्चे" },
  "common.unisex": { en: "Unisex", hi: "यूनिसेक्स" },
  "common.men": { en: "Men", hi: "पुरुष" },
  "common.women": { en: "Women", hi: "महिला" },
  "common.salon": { en: "Salon", hi: "सैलून" },
  "common.salons": { en: "Salons", hi: "सैलून" },
  "common.spa": { en: "Spa", hi: "स्पा" },
  "common.parlour": { en: "Parlour", hi: "पार्लर" },
  "common.booking": { en: "Booking", hi: "बुकिंग" },
  "common.bookings": { en: "Bookings", hi: "बुकिंग" },
  "common.review": { en: "Review", hi: "समीक्षा" },
  "common.writeReview": { en: "Write a Review", hi: "समीक्षा लिखें" },
  "common.rateReview": { en: "Rate & Review", hi: "रेट और समीक्षा" },
  "common.reviewed": { en: "Reviewed", hi: "समीक्षित" },
  "common.stars": { en: "stars", hi: "सितारे" },
  "common.prime": { en: "Prime", hi: "प्राइम" },
  "common.membership": { en: "Membership", hi: "सदस्यता" },
  "common.activatePrime": { en: "Activate Prime", hi: "प्राइम सक्रिय करें" },
  "common.daysRemaining": { en: "days remaining", hi: "दिन शेष" },
  "common.expiresOn": { en: "Expires on", hi: "समाप्त होता है" },
  "common.referral": { en: "Referral", hi: "रेफरल" },
  "common.referralCode": { en: "Referral Code", hi: "रेफरल कोड" },
  "common.waitlist": { en: "Waitlist", hi: "प्रतीक्षा सूची" },
  "common.joinWaitlist": { en: "Join Waitlist", hi: "प्रतीक्षा सूची में जुड़ें" },
  "common.position": { en: "Position", hi: "स्थान" },
  "common.notifications": { en: "Notifications", hi: "सूचनाएं" },
  "common.settings": { en: "Settings", hi: "सेटिंग्स" },
  "common.help": { en: "Help", hi: "सहायता" },
  "common.terms": { en: "Terms", hi: "नियम" },
  "common.privacy": { en: "Privacy", hi: "गोपनीयता" },
  "common.contact": { en: "Contact", hi: "संपर्क" },
  "common.about": { en: "About", hi: "के बारे में" },
  "common.copyright": { en: "All rights reserved", hi: "सर्वाधिकार सुरक्षित" },
  "common.poweredBy": { en: "Powered by", hi: "द्वारा संचालित" },
  "common.selectDate": { en: "Select Date", hi: "तारीख चुनें" },
  "common.selectTime": { en: "Select Time", hi: "समय चुनें" },
  "common.selectService": { en: "Select Service", hi: "सेवा चुनें" },
  "common.selectStaff": { en: "Select Staff", hi: "स्टाफ चुनें" },
  "common.anyStaff": { en: "Any Staff", hi: "कोई भी स्टाफ" },
  "common.noPreference": { en: "No Preference", hi: "कोई प्राथमिकता नहीं" },
  "common.confirm_booking": { en: "Confirm Booking", hi: "बुकिंग की पुष्टि करें" },
  "common.payment": { en: "Payment", hi: "भुगतान" },
  "common.payNow": { en: "Pay Now", hi: "अभी भुगतान करें" },
  "common.payLater": { en: "Pay at Salon", hi: "सैलून पर भुगतान करें" },
  "common.summary": { en: "Summary", hi: "सारांश" },
  "common.details": { en: "Details", hi: "विवरण" },
  "common.info": { en: "Info", hi: "जानकारी" },
  "common.photos": { en: "Photos", hi: "फोटो" },
  "common.videos": { en: "Videos", hi: "वीडियो" },
  "common.gallery": { en: "Gallery", hi: "गैलरी" },
  "common.location": { en: "Location", hi: "स्थान" },
  "common.hours": { en: "Hours", hi: "घंटे" },
  "common.openNow": { en: "Open Now", hi: "अभी खुला" },
  "common.closedNow": { en: "Closed Now", hi: "अभी बंद" },
  "common.nearMe": { en: "Near Me", hi: "मेरे पास" },
  "common.topRated": { en: "Top Rated", hi: "शीर्ष रेटेड" },
  "common.popular": { en: "Popular", hi: "लोकप्रिय" },
  "common.new": { en: "New", hi: "नया" },
  "common.featured": { en: "Featured", hi: "विशेष" },
  "common.trending": { en: "Trending", hi: "ट्रेंडिंग" },
  "common.recommended": { en: "Recommended", hi: "अनुशंसित" },
  "common.nearby": { en: "Nearby", hi: "पास में" },
  "common.pincode": { en: "Pincode", hi: "पिनकोड" },
  "common.state": { en: "State", hi: "राज्य" },
  "common.country": { en: "Country", hi: "देश" },
  "common.gender": { en: "Gender", hi: "लिंग" },
  "common.age": { en: "Age", hi: "आयु" },
  "common.dob": { en: "Date of Birth", hi: "जन्म तिथि" },
  "common.bio": { en: "Bio", hi: "परिचय" },
  "common.website": { en: "Website", hi: "वेबसाइट" },
  "common.social": { en: "Social", hi: "सोशल" },
  "common.instagram": { en: "Instagram", hi: "इंस्टाग्राम" },
  "common.facebook": { en: "Facebook", hi: "फेसबुक" },
  "common.twitter": { en: "Twitter", hi: "ट्विटर" },
  "common.youtube": { en: "YouTube", hi: "यूट्यूब" },
  "common.whatsapp": { en: "WhatsApp", hi: "व्हाट्सएप" },
  "common.owner": { en: "Owner", hi: "मालिक" },
  "common.customer": { en: "Customer", hi: "ग्राहक" },
  "common.admin": { en: "Admin", hi: "एडमिन" },
  "common.role": { en: "Role", hi: "भूमिका" },
  "common.user": { en: "User", hi: "उपयोगकर्ता" },
  "common.users": { en: "Users", hi: "उपयोगकर्ता" },
  "common.manage": { en: "Manage", hi: "प्रबंधित करें" },
  "common.approve": { en: "Approve", hi: "स्वीकृत करें" },
  "common.reject": { en: "Reject", hi: "अस्वीकृत करें" },
  "common.ban": { en: "Ban", hi: "प्रतिबंधित करें" },
  "common.unban": { en: "Unban", hi: "प्रतिबंध हटाएं" },
  "common.deactivate": { en: "Deactivate", hi: "निष्क्रिय करें" },
  "common.activate": { en: "Activate", hi: "सक्रिय करें" },
  "common.revenue": { en: "Revenue", hi: "राजस्व" },
  "common.analytics": { en: "Analytics", hi: "विश्लेषण" },
  "common.reports": { en: "Reports", hi: "रिपोर्ट" },
  "common.export": { en: "Export", hi: "निर्यात करें" },
  "common.import": { en: "Import", hi: "आयात करें" },
  "common.refresh": { en: "Refresh", hi: "ताज़ा करें" },
  "common.reset": { en: "Reset", hi: "रीसेट करें" },
  "common.clear": { en: "Clear", hi: "साफ करें" },
  "common.select": { en: "Select", hi: "चुनें" },
  "common.optional": { en: "Optional", hi: "वैकल्पिक" },
  "common.required": { en: "Required", hi: "आवश्यक" },
  "common.min": { en: "Min", hi: "न्यूनतम" },
  "common.max": { en: "Max", hi: "अधिकतम" },
  "common.free": { en: "Free", hi: "मुफ्त" },
  "common.premium": { en: "Premium", hi: "प्रीमियम" },
  "common.basic": { en: "Basic", hi: "बेसिक" },
  "common.standard": { en: "Standard", hi: "स्टैंडर्ड" },
  "common.pro": { en: "Pro", hi: "प्रो" },
  "common.enterprise": { en: "Enterprise", hi: "एंटरप्राइज" },
  "common.plan": { en: "Plan", hi: "योजना" },
  "common.upgrade": { en: "Upgrade", hi: "अपग्रेड करें" },
  "common.downgrade": { en: "Downgrade", hi: "डाउनग्रेड करें" },
  "common.subscribe": { en: "Subscribe", hi: "सदस्यता लें" },
  "common.unsubscribe": { en: "Unsubscribe", hi: "सदस्यता रद्द करें" },
  "common.renew": { en: "Renew", hi: "नवीनीकरण करें" },
  "common.expire": { en: "Expire", hi: "समाप्त" },
  "common.expired": { en: "Expired", hi: "समाप्त हो गया" },
  "common.valid": { en: "Valid", hi: "वैध" },
  "common.invalid": { en: "Invalid", hi: "अमान्य" },
  "common.success": { en: "Success", hi: "सफलता" },
  "common.failed": { en: "Failed", hi: "विफल" },
  "common.warning": { en: "Warning", hi: "चेतावनी" },
  "common.info_msg": { en: "Info", hi: "जानकारी" },
  "common.note": { en: "Note", hi: "नोट" },
  "common.tip": { en: "Tip", hi: "टिप" },
  "common.new_badge": { en: "New", hi: "नया" },
  "common.hot": { en: "Hot", hi: "हॉट" },
  "common.sale": { en: "Sale", hi: "सेल" },
  "common.offer": { en: "Offer", hi: "ऑफर" },
  "common.deal": { en: "Deal", hi: "डील" },
  "common.promo": { en: "Promo", hi: "प्रोमो" },
  "common.code": { en: "Code", hi: "कोड" },
  "common.enterCode": { en: "Enter Code", hi: "कोड दर्ज करें" },
  "common.applyCode": { en: "Apply Code", hi: "कोड लागू करें" },
  "common.removeCode": { en: "Remove Code", hi: "कोड हटाएं" },
  "common.invalidCode": { en: "Invalid Code", hi: "अमान्य कोड" },
  "common.validCode": { en: "Code Applied!", hi: "कोड लागू हुआ!" },
  "common.savedAmount": { en: "You saved", hi: "आपने बचाया" },
  "common.minOrder": { en: "Min. order", hi: "न्यूनतम ऑर्डर" },
  "common.maxDiscount": { en: "Max. discount", hi: "अधिकतम छूट" },
  "common.usageLimit": { en: "Usage limit", hi: "उपयोग सीमा" },
  "common.usedCount": { en: "Used", hi: "उपयोग किया" },
  "common.remaining": { en: "Remaining", hi: "शेष" },
  "common.expires": { en: "Expires", hi: "समाप्त होता है" },
  "common.created": { en: "Created", hi: "बनाया गया" },
  "common.updated": { en: "Updated", hi: "अपडेट किया गया" },
  "common.deleted": { en: "Deleted", hi: "हटाया गया" },
  "common.saved": { en: "Saved", hi: "सहेजा गया" },
  "common.submitted": { en: "Submitted", hi: "जमा किया गया" },
  "common.confirmed": { en: "Confirmed", hi: "पुष्टि की गई" },
  "common.scheduled": { en: "Scheduled", hi: "निर्धारित" },
  "common.inProgress": { en: "In Progress", hi: "प्रगति में" },
  "common.done": { en: "Done", hi: "हो गया" },
  "common.notFound": { en: "Not Found", hi: "नहीं मिला" },
  "common.goHome": { en: "Go Home", hi: "होम पर जाएं" },
  "common.goBack": { en: "Go Back", hi: "वापस जाएं" },
  "common.learnMore": { en: "Learn More", hi: "और जानें" },
  "common.getStarted": { en: "Get Started", hi: "शुरू करें" },
  "common.signUp": { en: "Sign Up", hi: "साइन अप करें" },
  "common.signIn": { en: "Sign In", hi: "साइन इन करें" },
  "common.forgotPassword": { en: "Forgot Password?", hi: "पासवर्ड भूल गए?" },
  "common.rememberMe": { en: "Remember Me", hi: "मुझे याद रखें" },
  "common.or_continue": { en: "Or continue with", hi: "या जारी रखें" },
  "common.alreadyAccount": {
    en: "Already have an account?",
    hi: "पहले से खाता है?",
  },
  "common.noAccount": { en: "Don't have an account?", hi: "खाता नहीं है?" },
  "common.createAccount": { en: "Create Account", hi: "खाता बनाएं" },
  "common.welcomeBack": { en: "Welcome Back!", hi: "वापसी पर स्वागत है!" },
  "common.welcome": { en: "Welcome", hi: "स्वागत है" },
  "common.hello": { en: "Hello", hi: "नमस्ते" },
  "common.hi": { en: "Hi", hi: "हाय" },
  "common.goodbye": { en: "Goodbye", hi: "अलविदा" },
  "common.thankYou": { en: "Thank You!", hi: "धन्यवाद!" },
  "common.sorryMsg": { en: "Sorry", hi: "माफ करें" },
  "common.pleaseWait": { en: "Please wait...", hi: "कृपया प्रतीक्षा करें..." },
  "common.processing_payment": {
    en: "Processing payment...",
    hi: "भुगतान प्रक्रिया में...",
  },
  "common.payment_success": { en: "Payment Successful!", hi: "भुगतान सफल!" },
  "common.payment_failed": { en: "Payment Failed", hi: "भुगतान विफल" },
  "common.booking_confirmed": {
    en: "Booking Confirmed!",
    hi: "बुकिंग की पुष्टि हुई!",
  },
  "common.booking_cancelled": { en: "Booking Cancelled", hi: "बुकिंग रद्द हुई" },
  "common.review_submitted": { en: "Review Submitted!", hi: "समीक्षा जमा हुई!" },
  "common.profile_updated": { en: "Profile Updated!", hi: "प्रोफाइल अपडेट हुई!" },
  "common.coupon_applied": { en: "Coupon Applied!", hi: "कूपन लागू हुआ!" },
  "common.coupon_removed": { en: "Coupon Removed", hi: "कूपन हटाया गया" },
  "common.copied": { en: "Copied!", hi: "कॉपी हुआ!" },
  "common.shared": { en: "Shared!", hi: "शेयर हुआ!" },
  "common.reported": { en: "Reported!", hi: "रिपोर्ट हुआ!" },
  "common.liked": { en: "Liked!", hi: "पसंद किया!" },
  "common.unliked": { en: "Unliked", hi: "नापसंद किया" },
  "common.followed": { en: "Followed!", hi: "फॉलो किया!" },
  "common.unfollowed": { en: "Unfollowed", hi: "अनफॉलो किया" },
  "common.commented": { en: "Comment Posted!", hi: "टिप्पणी पोस्ट हुई!" },
  "common.posted": { en: "Posted!", hi: "पोस्ट हुआ!" },
  "common.uploaded": { en: "Uploaded!", hi: "अपलोड हुआ!" },
  "common.downloaded": { en: "Downloaded!", hi: "डाउनलोड हुआ!" },
  "common.sent": { en: "Sent!", hi: "भेजा गया!" },
  "common.received": { en: "Received", hi: "प्राप्त हुआ" },
  "common.verified_badge": { en: "Verified", hi: "सत्यापित" },
  "common.unverified": { en: "Unverified", hi: "असत्यापित" },
  "common.certified": { en: "Certified", hi: "प्रमाणित" },
  "common.professional": { en: "Professional", hi: "पेशेवर" },
  "common.expert": { en: "Expert", hi: "विशेषज्ञ" },
  "common.beginner": { en: "Beginner", hi: "शुरुआती" },
  "common.intermediate": { en: "Intermediate", hi: "मध्यवर्ती" },
  "common.advanced": { en: "Advanced", hi: "उन्नत" },
  "common.experience": { en: "Experience", hi: "अनुभव" },
  "common.years": { en: "years", hi: "वर्ष" },
  "common.months": { en: "months", hi: "महीने" },
  "common.days": { en: "days", hi: "दिन" },
  "common.hours_unit": { en: "hours", hi: "घंटे" },
  "common.minutes_unit": { en: "minutes", hi: "मिनट" },
  "common.seconds": { en: "seconds", hi: "सेकंड" },
  "common.ago": { en: "ago", hi: "पहले" },
  "common.justNow": { en: "Just now", hi: "अभी" },
  "common.yesterday": { en: "Yesterday", hi: "कल" },
  "common.tomorrow": { en: "Tomorrow", hi: "कल" },
  "common.thisWeek": { en: "This Week", hi: "इस सप्ताह" },
  "common.lastWeek": { en: "Last Week", hi: "पिछले सप्ताह" },
  "common.thisMonth": { en: "This Month", hi: "इस महीने" },
  "common.lastMonth": { en: "Last Month", hi: "पिछले महीने" },
  "common.thisYear": { en: "This Year", hi: "इस वर्ष" },
  "common.lastYear": { en: "Last Year", hi: "पिछले वर्ष" },
  "common.custom": { en: "Custom", hi: "कस्टम" },
  "common.range": { en: "Range", hi: "सीमा" },
  "common.period": { en: "Period", hi: "अवधि" },
  "common.frequency": { en: "Frequency", hi: "आवृत्ति" },
  "common.daily": { en: "Daily", hi: "दैनिक" },
  "common.weekly": { en: "Weekly", hi: "साप्ताहिक" },
  "common.monthly": { en: "Monthly", hi: "मासिक" },
  "common.yearly": { en: "Yearly", hi: "वार्षिक" },
  "common.once": { en: "Once", hi: "एक बार" },
  "common.recurring": { en: "Recurring", hi: "आवर्ती" },
  "common.automatic": { en: "Automatic", hi: "स्वचालित" },
  "common.manual": { en: "Manual", hi: "मैनुअल" },
  "common.instant": { en: "Instant", hi: "तत्काल" },
  "common.scheduled_payout": { en: "Scheduled", hi: "निर्धारित" },
  "common.bank": { en: "Bank", hi: "बैंक" },
  "common.account": { en: "Account", hi: "खाता" },
  "common.ifsc": { en: "IFSC", hi: "आईएफएससी" },
  "common.upi": { en: "UPI", hi: "यूपीआई" },
  "common.card": { en: "Card", hi: "कार्ड" },
  "common.cash": { en: "Cash", hi: "नकद" },
  "common.online": { en: "Online", hi: "ऑनलाइन" },
  "common.offline": { en: "Offline", hi: "ऑफलाइन" },
  "common.digital": { en: "Digital", hi: "डिजिटल" },
  "common.physical": { en: "Physical", hi: "भौतिक" },
  "common.virtual": { en: "Virtual", hi: "वर्चुअल" },
  "common.hybrid": { en: "Hybrid", hi: "हाइब्रिड" },
  "common.inPerson": { en: "In Person", hi: "व्यक्तिगत रूप से" },
  "common.atHome": { en: "At Home", hi: "घर पर" },
  "common.atSalon": { en: "At Salon", hi: "सैलून पर" },
  "common.doorstep": { en: "Doorstep", hi: "दरवाजे पर" },
  "common.pickup": { en: "Pickup", hi: "पिकअप" },
  "common.delivery": { en: "Delivery", hi: "डिलीवरी" },
  "common.express": { en: "Express", hi: "एक्सप्रेस" },
  "common.standard_delivery": { en: "Standard", hi: "स्टैंडर्ड" },
  "common.economy": { en: "Economy", hi: "इकोनॉमी" },
  "common.priority": { en: "Priority", hi: "प्राथमिकता" },
  "common.urgent": { en: "Urgent", hi: "जरूरी" },
  "common.normal": { en: "Normal", hi: "सामान्य" },
  "common.low": { en: "Low", hi: "कम" },
  "common.medium": { en: "Medium", hi: "मध्यम" },
  "common.high": { en: "High", hi: "उच्च" },
  "common.critical": { en: "Critical", hi: "गंभीर" },
  "common.moderate": { en: "Moderate", hi: "मध्यम" },
  "common.severe": { en: "Severe", hi: "गंभीर" },
  "common.mild": { en: "Mild", hi: "हल्का" },
  "common.strong": { en: "Strong", hi: "मजबूत" },
  "common.weak": { en: "Weak", hi: "कमजोर" },
  "common.good": { en: "Good", hi: "अच्छा" },
  "common.bad": { en: "Bad", hi: "बुरा" },
  "common.excellent": { en: "Excellent", hi: "उत्कृष्ट" },
  "common.poor": { en: "Poor", hi: "खराब" },
  "common.average": { en: "Average", hi: "औसत" },
  "common.above_average": { en: "Above Average", hi: "औसत से ऊपर" },
  "common.below_average": { en: "Below Average", hi: "औसत से नीचे" },
  "common.satisfactory": { en: "Satisfactory", hi: "संतोषजनक" },
  "common.unsatisfactory": { en: "Unsatisfactory", hi: "असंतोषजनक" },
  "common.outstanding": { en: "Outstanding", hi: "उत्कृष्ट" },
  "common.exceptional": { en: "Exceptional", hi: "असाधारण" },
  "common.remarkable": { en: "Remarkable", hi: "उल्लेखनीय" },
  "common.impressive": { en: "Impressive", hi: "प्रभावशाली" },
  "common.disappointing": { en: "Disappointing", hi: "निराशाजनक" },
  "common.terrible": { en: "Terrible", hi: "भयानक" },
  "common.horrible": { en: "Horrible", hi: "भयंकर" },
  "common.amazing": { en: "Amazing", hi: "अद्भुत" },
  "common.wonderful": { en: "Wonderful", hi: "शानदार" },
  "common.fantastic": { en: "Fantastic", hi: "शानदार" },
  "common.great": { en: "Great", hi: "बढ़िया" },
  "common.nice": { en: "Nice", hi: "अच्छा" },
  "common.okay": { en: "Okay", hi: "ठीक है" },
  "common.notBad": { en: "Not Bad", hi: "बुरा नहीं" },
  "common.couldBeBetter": { en: "Could Be Better", hi: "बेहतर हो सकता था" },
  "common.needsImprovement": { en: "Needs Improvement", hi: "सुधार की जरूरत है" },
  "common.unacceptable": { en: "Unacceptable", hi: "अस्वीकार्य" },

  // Home page
  "home.hero.title": {
    en: "India's Premier Salon Booking Platform",
    hi: "भारत का प्रमुख सैलून बुकिंग प्लेटफॉर्म",
  },
  "home.hero.subtitle": {
    en: "Discover top salons, book instantly, look amazing",
    hi: "शीर्ष सैलून खोजें, तुरंत बुक करें, शानदार दिखें",
  },
  "home.hero.searchPlaceholder": {
    en: "Search salons by city or pincode...",
    hi: "शहर या पिनकोड से सैलून खोजें...",
  },
  "home.stats.salons": { en: "Salons", hi: "सैलून" },
  "home.stats.bookings": { en: "Bookings", hi: "बुकिंग" },
  "home.stats.cities": { en: "Cities", hi: "शहर" },
  "home.stats.customers": { en: "Happy Customers", hi: "खुश ग्राहक" },
  "home.categories.title": { en: "Browse by Category", hi: "श्रेणी के अनुसार खोजें" },
  "home.featured.title": { en: "Featured Salons", hi: "विशेष सैलून" },
  "home.howItWorks.title": { en: "How It Works", hi: "यह कैसे काम करता है" },
  "home.howItWorks.step1": { en: "Search & Discover", hi: "खोजें और खोजें" },
  "home.howItWorks.step2": { en: "Choose & Book", hi: "चुनें और बुक करें" },
  "home.howItWorks.step3": { en: "Pay & Enjoy", hi: "भुगतान करें और आनंद लें" },
  "home.prime.title": { en: "Go Prime", hi: "प्राइम बनें" },
  "home.prime.subtitle": {
    en: "Exclusive discounts on every booking",
    hi: "हर बुकिंग पर विशेष छूट",
  },
  "home.cta.title": { en: "Own a Salon?", hi: "सैलून के मालिक हैं?" },
  "home.cta.subtitle": {
    en: "Join thousands of salon owners growing their business",
    hi: "हजारों सैलून मालिकों के साथ जुड़ें",
  },
  "home.cta.button": { en: "Register Your Salon", hi: "अपना सैलून रजिस्टर करें" },

  // Search
  "search.title": { en: "Find Salons", hi: "सैलून खोजें" },
  "search.filters": { en: "Filters", hi: "फ़िल्टर" },
  "search.sortBy": { en: "Sort By", hi: "क्रमबद्ध करें" },
  "search.results": { en: "results found", hi: "परिणाम मिले" },
  "search.noResults": { en: "No salons found", hi: "कोई सैलून नहीं मिला" },
  "search.tryDifferent": { en: "Try different filters", hi: "अलग फ़िल्टर आज़माएं" },
  "search.priceRange": { en: "Price Range", hi: "मूल्य सीमा" },
  "search.minRating": { en: "Min Rating", hi: "न्यूनतम रेटिंग" },
  "search.openNow": { en: "Open Now", hi: "अभी खुला" },
  "search.category": { en: "Category", hi: "श्रेणी" },
  "search.clearFilters": { en: "Clear Filters", hi: "फ़िल्टर साफ करें" },
  "search.applyFilters": { en: "Apply Filters", hi: "फ़िल्टर लागू करें" },

  // Salon Detail
  "salon.about": { en: "About", hi: "के बारे में" },
  "salon.services": { en: "Services", hi: "सेवाएं" },
  "salon.staff": { en: "Staff", hi: "स्टाफ" },
  "salon.reviews": { en: "Reviews", hi: "समीक्षाएं" },
  "salon.photos": { en: "Photos", hi: "फोटो" },
  "salon.location": { en: "Location", hi: "स्थान" },
  "salon.timings": { en: "Timings", hi: "समय" },
  "salon.amenities": { en: "Amenities", hi: "सुविधाएं" },
  "salon.noReviews": { en: "No reviews yet", hi: "अभी तक कोई समीक्षा नहीं" },
  "salon.beFirst": { en: "Be the first to review!", hi: "पहले समीक्षा करें!" },

  // Booking
  "booking.selectService": { en: "Select Service", hi: "सेवा चुनें" },
  "booking.selectDate": { en: "Select Date", hi: "तारीख चुनें" },
  "booking.selectSlot": { en: "Select Time Slot", hi: "समय स्लॉट चुनें" },
  "booking.selectStaff": { en: "Select Staff", hi: "स्टाफ चुनें" },
  "booking.summary": { en: "Booking Summary", hi: "बुकिंग सारांश" },
  "booking.payment": { en: "Payment", hi: "भुगतान" },
  "booking.confirm": { en: "Confirm Booking", hi: "बुकिंग की पुष्टि करें" },
  "booking.timerLabel": { en: "Slot reserved for", hi: "स्लॉट आरक्षित है" },
  "booking.timerExpired": {
    en: "Slot reservation expired. Please select again.",
    hi: "स्लॉट आरक्षण समाप्त हो गया। कृपया फिर से चुनें।",
  },
  "booking.noSlots": {
    en: "No slots available for this date",
    hi: "इस तारीख के लिए कोई स्लॉट उपलब्ध नहीं",
  },
  "booking.slotBooked": { en: "Already Booked", hi: "पहले से बुक" },
  "booking.couponCode": { en: "Coupon Code", hi: "कूपन कोड" },
  "booking.primeDiscount": { en: "Prime Discount", hi: "प्राइम छूट" },
  "booking.couponDiscount": { en: "Coupon Discount", hi: "कूपन छूट" },
  "booking.finalAmount": { en: "Final Amount", hi: "अंतिम राशि" },
  "booking.step1": { en: "Service", hi: "सेवा" },
  "booking.step2": { en: "Date & Time", hi: "तारीख और समय" },
  "booking.step3": { en: "Staff", hi: "स्टाफ" },
  "booking.step4": { en: "Summary", hi: "सारांश" },

  // Customer Bookings
  "bookings.title": { en: "My Bookings", hi: "मेरी बुकिंग" },
  "bookings.upcoming": { en: "Upcoming", hi: "आगामी" },
  "bookings.past": { en: "Past", hi: "पिछली" },
  "bookings.all": { en: "All", hi: "सभी" },
  "bookings.noBookings": { en: "No bookings found", hi: "कोई बुकिंग नहीं मिली" },
  "bookings.bookFirst": {
    en: "Book your first appointment!",
    hi: "अपनी पहली अपॉइंटमेंट बुक करें!",
  },
  "bookings.cancelBooking": { en: "Cancel Booking", hi: "बुकिंग रद्द करें" },
  "bookings.reschedule": { en: "Reschedule", hi: "पुनर्निर्धारित करें" },
  "bookings.viewDetails": { en: "View Details", hi: "विवरण देखें" },
  "bookings.addToCalendar": { en: "Add to Calendar", hi: "कैलेंडर में जोड़ें" },
  "bookings.getDirections": { en: "Get Directions", hi: "दिशा-निर्देश प्राप्त करें" },
  "bookings.callSalon": { en: "Call Salon", hi: "सैलून को कॉल करें" },
  "bookings.rateService": { en: "Rate Service", hi: "सेवा रेट करें" },
  "bookings.reviewed": { en: "Reviewed", hi: "समीक्षित" },

  // Profile
  "profile.title": { en: "My Profile", hi: "मेरी प्रोफाइल" },
  "profile.editProfile": { en: "Edit Profile", hi: "प्रोफाइल संपादित करें" },
  "profile.personalInfo": { en: "Personal Information", hi: "व्यक्तिगत जानकारी" },
  "profile.preferences": { en: "Preferences", hi: "प्राथमिकताएं" },
  "profile.security": { en: "Security", hi: "सुरक्षा" },
  "profile.notifications": { en: "Notifications", hi: "सूचनाएं" },
  "profile.language": { en: "Language", hi: "भाषा" },
  "profile.theme": { en: "Theme", hi: "थीम" },
  "profile.darkMode": { en: "Dark Mode", hi: "डार्क मोड" },
  "profile.lightMode": { en: "Light Mode", hi: "लाइट मोड" },
  "profile.referralCode": { en: "Your Referral Code", hi: "आपका रेफरल कोड" },
  "profile.referralEarnings": { en: "Referral Earnings", hi: "रेफरल कमाई" },
  "profile.totalReferrals": { en: "Total Referrals", hi: "कुल रेफरल" },
  "profile.memberSince": { en: "Member Since", hi: "सदस्य बने" },
  "profile.principalId": { en: "Principal ID", hi: "प्रिंसिपल आईडी" },
  "profile.logout": { en: "Logout", hi: "लॉगआउट" },
  "profile.deleteAccount": { en: "Delete Account", hi: "खाता हटाएं" },
  "profile.firstName": { en: "First Name", hi: "पहला नाम" },
  "profile.lastName": { en: "Last Name", hi: "अंतिम नाम" },
  "profile.fullName": { en: "Full Name", hi: "पूरा नाम" },
  "profile.gender": { en: "Gender", hi: "लिंग" },
  "profile.phone": { en: "Phone Number", hi: "फोन नंबर" },
  "profile.address": { en: "Address", hi: "पता" },
  "profile.city": { en: "City", hi: "शहर" },
  "profile.pincode": { en: "Pincode", hi: "पिनकोड" },
  "profile.state": { en: "State", hi: "राज्य" },
  "profile.photo": { en: "Profile Photo", hi: "प्रोफाइल फोटो" },
  "profile.changePhoto": { en: "Change Photo", hi: "फोटो बदलें" },
  "profile.saveChanges": { en: "Save Changes", hi: "बदलाव सहेजें" },
  "profile.discardChanges": { en: "Discard Changes", hi: "बदलाव रद्द करें" },

  // Wallet
  "wallet.title": { en: "My Wallet", hi: "मेरा वॉलेट" },
  "wallet.balance": { en: "Wallet Balance", hi: "वॉलेट बैलेंस" },
  "wallet.addMoney": { en: "Add Money", hi: "पैसे जोड़ें" },
  "wallet.withdraw": { en: "Withdraw", hi: "निकालें" },
  "wallet.transactions": { en: "Transactions", hi: "लेनदेन" },
  "wallet.noTransactions": {
    en: "No transactions yet",
    hi: "अभी तक कोई लेनदेन नहीं",
  },
  "wallet.credit": { en: "Credit", hi: "क्रेडिट" },
  "wallet.debit": { en: "Debit", hi: "डेबिट" },
  "wallet.refund": { en: "Refund", hi: "रिफंड" },
  "wallet.cashback": { en: "Cashback", hi: "कैशबैक" },
  "wallet.reward": { en: "Reward", hi: "इनाम" },
  "wallet.bonus": { en: "Bonus", hi: "बोनस" },
  "wallet.primeStatus": { en: "Prime Status", hi: "प्राइम स्थिति" },
  "wallet.primeActive": { en: "Prime Active", hi: "प्राइम सक्रिय" },
  "wallet.primeInactive": { en: "Prime Inactive", hi: "प्राइम निष्क्रिय" },
  "wallet.primeBenefits": { en: "Prime Benefits", hi: "प्राइम लाभ" },
  "wallet.primeDiscount": {
    en: "Exclusive discount on every booking",
    hi: "हर बुकिंग पर विशेष छूट",
  },
  "wallet.activatePrime": { en: "Activate Prime", hi: "प्राइम सक्रिय करें" },
  "wallet.primeExpiry": { en: "Prime expires on", hi: "प्राइम समाप्त होता है" },
  "wallet.primeDaysLeft": { en: "days left", hi: "दिन शेष" },

  // Social Feed
  "feed.title": { en: "Social Feed", hi: "सोशल फीड" },
  "feed.trending": { en: "Trending", hi: "ट्रेंडिंग" },
  "feed.following": { en: "Following", hi: "फॉलोइंग" },
  "feed.createPost": { en: "Create Post", hi: "पोस्ट बनाएं" },
  "feed.addCaption": { en: "Add a caption...", hi: "कैप्शन जोड़ें..." },
  "feed.noFeed": { en: "No posts yet", hi: "अभी तक कोई पोस्ट नहीं" },
  "feed.followSalons": {
    en: "Follow salons to see their posts",
    hi: "पोस्ट देखने के लिए सैलून फॉलो करें",
  },
  "feed.likes": { en: "likes", hi: "पसंद" },
  "feed.comments": { en: "comments", hi: "टिप्पणियां" },
  "feed.addComment": { en: "Add a comment...", hi: "टिप्पणी जोड़ें..." },
  "feed.viewComments": { en: "View all comments", hi: "सभी टिप्पणियां देखें" },
  "feed.reportPost": { en: "Report Post", hi: "पोस्ट रिपोर्ट करें" },
  "feed.deletePost": { en: "Delete Post", hi: "पोस्ट हटाएं" },
  "feed.editPost": { en: "Edit Post", hi: "पोस्ट संपादित करें" },
  "feed.sharePost": { en: "Share Post", hi: "पोस्ट शेयर करें" },
  "feed.bookFromPost": { en: "Book Now", hi: "अभी बुक करें" },

  // Owner Dashboard
  "owner.dashboard": { en: "Dashboard", hi: "डैशबोर्ड" },
  "owner.bookings": { en: "Bookings", hi: "बुकिंग" },
  "owner.schedule": { en: "Schedule", hi: "शेड्यूल" },
  "owner.earnings": { en: "Earnings", hi: "कमाई" },
  "owner.promotions": { en: "Promotions", hi: "प्रमोशन" },
  "owner.content": { en: "Content", hi: "कंटेंट" },
  "owner.settings": { en: "Settings", hi: "सेटिंग्स" },
  "owner.acceptBooking": { en: "Accept", hi: "स्वीकार करें" },
  "owner.declineBooking": { en: "Decline", hi: "अस्वीकार करें" },
  "owner.completeBooking": { en: "Mark Complete", hi: "पूर्ण चिह्नित करें" },
  "owner.totalBookings": { en: "Total Bookings", hi: "कुल बुकिंग" },
  "owner.todayBookings": { en: "Today's Bookings", hi: "आज की बुकिंग" },
  "owner.pendingBookings": { en: "Pending", hi: "लंबित" },
  "owner.totalEarnings": { en: "Total Earnings", hi: "कुल कमाई" },
  "owner.payableBalance": { en: "Payable Balance", hi: "देय शेष" },
  "owner.commissionDeducted": {
    en: "Commission Deducted",
    hi: "कमीशन काटा गया",
  },
  "owner.requestPayout": { en: "Request Payout", hi: "भुगतान का अनुरोध करें" },
  "owner.payoutHistory": { en: "Payout History", hi: "भुगतान इतिहास" },
  "owner.createCoupon": { en: "Create Coupon", hi: "कूपन बनाएं" },
  "owner.activeCoupons": { en: "Active Coupons", hi: "सक्रिय कूपन" },
  "owner.uploadPhoto": { en: "Upload Photo", hi: "फोटो अपलोड करें" },
  "owner.salonPhotos": { en: "Salon Photos", hi: "सैलून फोटो" },
  "owner.markHoliday": { en: "Mark Holiday", hi: "छुट्टी चिह्नित करें" },
  "owner.removeHoliday": { en: "Remove Holiday", hi: "छुट्टी हटाएं" },
  "owner.addSlot": { en: "Add Slot", hi: "स्लॉट जोड़ें" },
  "owner.removeSlot": { en: "Remove Slot", hi: "स्लॉट हटाएं" },
  "owner.weeklyCalendar": { en: "Weekly Calendar", hi: "साप्ताहिक कैलेंडर" },
  "owner.slotManagement": { en: "Slot Management", hi: "स्लॉट प्रबंधन" },
  "owner.earningsChart": { en: "Earnings Chart", hi: "कमाई चार्ट" },
  "owner.noEarnings": { en: "No earnings data", hi: "कोई कमाई डेटा नहीं" },
  "owner.noCoupons": { en: "No coupons created", hi: "कोई कूपन नहीं बनाया" },
  "owner.noPhotos": { en: "No photos uploaded", hi: "कोई फोटो अपलोड नहीं" },
  "owner.salonNotApproved": {
    en: "Salon not approved yet",
    hi: "सैलून अभी तक स्वीकृत नहीं",
  },
  "owner.pendingApproval": { en: "Pending Approval", hi: "स्वीकृति लंबित" },

  // Admin Panel
  "admin.title": { en: "Admin Panel", hi: "एडमिन पैनल" },
  "admin.approvals": { en: "Approvals", hi: "स्वीकृतियां" },
  "admin.users": { en: "Users", hi: "उपयोगकर्ता" },
  "admin.commission": { en: "Commission", hi: "कमीशन" },
  "admin.payouts": { en: "Payouts", hi: "भुगतान" },
  "admin.analytics": { en: "Analytics", hi: "विश्लेषण" },
  "admin.moderation": { en: "Moderation", hi: "मॉडरेशन" },
  "admin.disputes": { en: "Disputes", hi: "विवाद" },
  "admin.stripe": { en: "Stripe Config", hi: "स्ट्राइप कॉन्फिग" },
  "admin.cms": { en: "CMS", hi: "सीएमएस" },
  "admin.blog": { en: "Blog Posts", hi: "ब्लॉग पोस्ट" },
  "admin.faq": { en: "FAQ", hi: "एफएक्यू" },
  "admin.contactMessages": { en: "Contact Messages", hi: "संपर्क संदेश" },
  "admin.approveSalon": { en: "Approve Salon", hi: "सैलून स्वीकृत करें" },
  "admin.rejectSalon": { en: "Reject Salon", hi: "सैलून अस्वीकृत करें" },
  "admin.setCommission": { en: "Set Commission", hi: "कमीशन सेट करें" },
  "admin.processPayout": { en: "Process Payout", hi: "भुगतान प्रक्रिया करें" },
  "admin.banUser": { en: "Ban User", hi: "उपयोगकर्ता प्रतिबंधित करें" },
  "admin.unbanUser": { en: "Unban User", hi: "प्रतिबंध हटाएं" },
  "admin.changeRole": { en: "Change Role", hi: "भूमिका बदलें" },
  "admin.viewDetails": { en: "View Details", hi: "विवरण देखें" },
  "admin.totalRevenue": { en: "Total Revenue", hi: "कुल राजस्व" },
  "admin.totalCommission": { en: "Total Commission", hi: "कुल कमीशन" },
  "admin.pendingPayouts": { en: "Pending Payouts", hi: "लंबित भुगतान" },
  "admin.activeUsers": { en: "Active Users", hi: "सक्रिय उपयोगकर्ता" },
  "admin.activeSalons": { en: "Active Salons", hi: "सक्रिय सैलून" },
  "admin.reportedContent": {
    en: "Reported Content",
    hi: "रिपोर्ट किया गया कंटेंट",
  },
  "admin.resolveDispute": { en: "Resolve Dispute", hi: "विवाद हल करें" },
  "admin.markRead": { en: "Mark as Read", hi: "पढ़ा हुआ चिह्नित करें" },
  "admin.createBlogPost": { en: "Create Blog Post", hi: "ब्लॉग पोस्ट बनाएं" },
  "admin.addFAQ": { en: "Add FAQ", hi: "एफएक्यू जोड़ें" },
  "admin.deleteFAQ": { en: "Delete FAQ", hi: "एफएक्यू हटाएं" },
  "admin.deletePost": { en: "Delete Post", hi: "पोस्ट हटाएं" },
  "admin.noMessages": { en: "No contact messages", hi: "कोई संपर्क संदेश नहीं" },
  "admin.noPosts": { en: "No blog posts", hi: "कोई ब्लॉग पोस्ट नहीं" },
  "admin.noFAQs": { en: "No FAQs", hi: "कोई एफएक्यू नहीं" },
  "admin.noApprovals": {
    en: "No pending approvals",
    hi: "कोई लंबित स्वीकृति नहीं",
  },
  "admin.noDisputes": { en: "No disputes", hi: "कोई विवाद नहीं" },
  "admin.noReported": {
    en: "No reported content",
    hi: "कोई रिपोर्ट किया गया कंटेंट नहीं",
  },
  "admin.globalCommission": {
    en: "Global Commission Rate",
    hi: "वैश्विक कमीशन दर",
  },
  "admin.categoryCommission": { en: "Category Commission", hi: "श्रेणी कमीशन" },
  "admin.salonCommission": { en: "Salon Commission", hi: "सैलून कमीशन" },
  "admin.primeDiscount": { en: "Prime Discount %", hi: "प्राइम छूट %" },
  "admin.stripeConfigured": {
    en: "Stripe Configured",
    hi: "स्ट्राइप कॉन्फिगर किया गया",
  },
  "admin.stripeNotConfigured": {
    en: "Stripe Not Configured",
    hi: "स्ट्राइप कॉन्फिगर नहीं",
  },
  "admin.configureStripe": { en: "Configure Stripe", hi: "स्ट्राइप कॉन्फिगर करें" },

  // Blog
  "blog.title": { en: "Blog", hi: "ब्लॉग" },
  "blog.subtitle": {
    en: "Tips, trends, and stories from the world of beauty",
    hi: "सौंदर्य की दुनिया से टिप्स, ट्रेंड और कहानियां",
  },
  "blog.readMore": { en: "Read More", hi: "और पढ़ें" },
  "blog.publishedOn": { en: "Published on", hi: "प्रकाशित" },
  "blog.by": { en: "by", hi: "द्वारा" },
  "blog.noPosts": { en: "No blog posts yet", hi: "अभी तक कोई ब्लॉग पोस्ट नहीं" },
  "blog.backToBlog": { en: "Back to Blog", hi: "ब्लॉग पर वापस" },
  "blog.notFound": { en: "Post not found", hi: "पोस्ट नहीं मिली" },
  "blog.latestPosts": { en: "Latest Posts", hi: "नवीनतम पोस्ट" },
  "blog.categories": { en: "Categories", hi: "श्रेणियां" },
  "blog.tags": { en: "Tags", hi: "टैग" },
  "blog.share": { en: "Share this post", hi: "यह पोस्ट शेयर करें" },
  "blog.relatedPosts": { en: "Related Posts", hi: "संबंधित पोस्ट" },
  "blog.minRead": { en: "min read", hi: "मिनट पढ़ें" },
  "blog.views": { en: "views", hi: "व्यूज" },
  "blog.author": { en: "Author", hi: "लेखक" },
  "blog.coverImage": { en: "Cover Image URL", hi: "कवर इमेज URL" },
  "blog.body": { en: "Post Body", hi: "पोस्ट बॉडी" },
  "blog.excerpt": { en: "Excerpt", hi: "अंश" },
  "blog.createPost": { en: "Create Post", hi: "पोस्ट बनाएं" },
  "blog.editPost": { en: "Edit Post", hi: "पोस्ट संपादित करें" },
  "blog.deletePost": { en: "Delete Post", hi: "पोस्ट हटाएं" },
  "blog.publishPost": { en: "Publish Post", hi: "पोस्ट प्रकाशित करें" },
  "blog.draftPost": { en: "Save as Draft", hi: "ड्राफ्ट के रूप में सहेजें" },
  "blog.published": { en: "Published", hi: "प्रकाशित" },
  "blog.draft": { en: "Draft", hi: "ड्राफ्ट" },

  // FAQ
  "faq.title": { en: "Frequently Asked Questions", hi: "अक्सर पूछे जाने वाले प्रश्न" },
  "faq.subtitle": {
    en: "Find answers to common questions about Haircut.com",
    hi: "Haircut.com के बारे में सामान्य प्रश्नों के उत्तर खोजें",
  },
  "faq.searchPlaceholder": { en: "Search FAQs...", hi: "एफएक्यू खोजें..." },
  "faq.noResults": { en: "No FAQs found", hi: "कोई एफएक्यू नहीं मिला" },
  "faq.category.bookings": { en: "Bookings", hi: "बुकिंग" },
  "faq.category.payments": { en: "Payments", hi: "भुगतान" },
  "faq.category.salonOwners": { en: "Salon Owners", hi: "सैलून मालिक" },
  "faq.category.account": { en: "Account", hi: "खाता" },
  "faq.category.general": { en: "General", hi: "सामान्य" },
  "faq.stillHaveQuestions": {
    en: "Still have questions?",
    hi: "अभी भी प्रश्न हैं?",
  },
  "faq.contactUs": { en: "Contact Us", hi: "हमसे संपर्क करें" },
  "faq.question": { en: "Question", hi: "प्रश्न" },
  "faq.answer": { en: "Answer", hi: "उत्तर" },
  "faq.addQuestion": { en: "Add Question", hi: "प्रश्न जोड़ें" },
  "faq.editQuestion": { en: "Edit Question", hi: "प्रश्न संपादित करें" },
  "faq.deleteQuestion": { en: "Delete Question", hi: "प्रश्न हटाएं" },

  // Contact
  "contact.title": { en: "Contact Us", hi: "हमसे संपर्क करें" },
  "contact.subtitle": {
    en: "We'd love to hear from you",
    hi: "हम आपसे सुनना चाहते हैं",
  },
  "contact.form.title": { en: "Send us a Message", hi: "हमें संदेश भेजें" },
  "contact.form.name": { en: "Your Name", hi: "आपका नाम" },
  "contact.form.email": { en: "Your Email", hi: "आपका ईमेल" },
  "contact.form.subject": { en: "Subject", hi: "विषय" },
  "contact.form.message": { en: "Your Message", hi: "आपका संदेश" },
  "contact.form.submit": { en: "Send Message", hi: "संदेश भेजें" },
  "contact.form.success": {
    en: "Message sent successfully!",
    hi: "संदेश सफलतापूर्वक भेजा गया!",
  },
  "contact.form.error": {
    en: "Failed to send message. Please try again.",
    hi: "संदेश भेजने में विफल। कृपया पुनः प्रयास करें।",
  },
  "contact.info.title": { en: "Get in Touch", hi: "संपर्क करें" },
  "contact.info.founder": { en: "Founder & CEO", hi: "संस्थापक और सीईओ" },
  "contact.info.address": { en: "Address", hi: "पता" },
  "contact.info.phone": { en: "Phone", hi: "फोन" },
  "contact.info.email": { en: "Email", hi: "ईमेल" },
  "contact.info.hours": { en: "Support Hours", hi: "सहायता घंटे" },
  "contact.info.hoursValue": {
    en: "Mon-Sat, 9 AM - 6 PM IST",
    hi: "सोम-शनि, सुबह 9 - शाम 6 बजे IST",
  },
  "contact.social.title": { en: "Follow Us", hi: "हमें फॉलो करें" },

  // Terms & Privacy
  "terms.title": { en: "Terms & Conditions", hi: "नियम और शर्तें" },
  "terms.lastUpdated": { en: "Last Updated", hi: "अंतिम अपडेट" },
  "privacy.title": { en: "Privacy Policy", hi: "गोपनीयता नीति" },
  "privacy.lastUpdated": { en: "Last Updated", hi: "अंतिम अपडेट" },

  // Payment
  "payment.success.title": { en: "Payment Successful!", hi: "भुगतान सफल!" },
  "payment.success.subtitle": {
    en: "Your booking has been confirmed",
    hi: "आपकी बुकिंग की पुष्टि हो गई है",
  },
  "payment.failed.title": { en: "Payment Failed", hi: "भुगतान विफल" },
  "payment.failed.subtitle": {
    en: "Your payment could not be processed",
    hi: "आपका भुगतान प्रक्रिया नहीं हो सका",
  },
  "payment.retry": { en: "Retry Payment", hi: "भुगतान पुनः प्रयास करें" },
  "payment.viewBooking": { en: "View Booking", hi: "बुकिंग देखें" },
  "payment.goHome": { en: "Go to Home", hi: "होम पर जाएं" },

  // Registration
  "register.title": { en: "Register Your Salon", hi: "अपना सैलून रजिस्टर करें" },
  "register.step1": { en: "Shop Info", hi: "दुकान की जानकारी" },
  "register.step2": { en: "Services", hi: "सेवाएं" },
  "register.step3": { en: "Working Hours", hi: "काम के घंटे" },
  "register.step4": { en: "Bank Details", hi: "बैंक विवरण" },
  "register.step5": { en: "Documents", hi: "दस्तावेज" },
  "register.pending.title": {
    en: "Registration Submitted!",
    hi: "रजिस्ट्रेशन जमा हुआ!",
  },
  "register.pending.subtitle": {
    en: "Your salon is under review",
    hi: "आपका सैलून समीक्षा में है",
  },
  "register.pending.timeline": {
    en: "Expected approval: 24-48 hours",
    hi: "अपेक्षित स्वीकृति: 24-48 घंटे",
  },

  // Login
  "login.title": { en: "Welcome to Haircut.com", hi: "Haircut.com पर स्वागत है" },
  "login.subtitle": {
    en: "India's Premier Salon Booking Platform",
    hi: "भारत का प्रमुख सैलून बुकिंग प्लेटफॉर्म",
  },
  "login.button": {
    en: "Login with Internet Identity",
    hi: "इंटरनेट आइडेंटिटी से लॉगिन करें",
  },
  "login.loggingIn": { en: "Logging in...", hi: "लॉगिन हो रहा है..." },
  "login.secure": { en: "Secure & Decentralized", hi: "सुरक्षित और विकेंद्रीकृत" },
  "login.noPassword": { en: "No password needed", hi: "पासवर्ड की जरूरत नहीं" },
  "login.privacyFirst": { en: "Privacy first", hi: "गोपनीयता पहले" },

  // Profile Setup
  "setup.title": { en: "Complete Your Profile", hi: "अपनी प्रोफाइल पूरी करें" },
  "setup.subtitle": {
    en: "Tell us a bit about yourself",
    hi: "हमें अपने बारे में थोड़ा बताएं",
  },
  "setup.namePlaceholder": {
    en: "Enter your full name",
    hi: "अपना पूरा नाम दर्ज करें",
  },
  "setup.genderLabel": { en: "Select Gender", hi: "लिंग चुनें" },
  "setup.continue": { en: "Continue", hi: "जारी रखें" },

  // Error pages
  "error.404.title": { en: "Page Not Found", hi: "पेज नहीं मिला" },
  "error.404.subtitle": {
    en: "The page you're looking for doesn't exist",
    hi: "जो पेज आप ढूंढ रहे हैं वह मौजूद नहीं है",
  },
  "error.500.title": { en: "Server Error", hi: "सर्वर त्रुटि" },
  "error.500.subtitle": {
    en: "Something went wrong on our end",
    hi: "हमारी तरफ से कुछ गलत हुआ",
  },
  "error.unauthorized.title": { en: "Access Denied", hi: "पहुंच अस्वीकृत" },
  "error.unauthorized.subtitle": {
    en: "You don't have permission to view this page",
    hi: "आपको यह पेज देखने की अनुमति नहीं है",
  },
};

const AppContext = createContext<AppContextType | undefined>(undefined);

export function AppProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("haircut_language");
    return (saved as Language) || "en";
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("haircut_language", lang);
  };

  const t = (key: string): string => {
    const translation = translations[key];
    if (!translation) return key;
    return translation[language] || translation.en || key;
  };

  useEffect(() => {
    document.documentElement.lang = language === "hi" ? "hi" : "en";
  }, [language]);

  return (
    <AppContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </AppContext.Provider>
  );
}

export function useApp() {
  const context = useContext(AppContext);
  if (!context) {
    throw new Error("useApp must be used within AppProvider");
  }
  return context;
}
